/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as IdeasIdRouteImport } from './routes/ideas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdRoute = IdeasIdRouteImport.update({
  id: '/ideas/$id',
  path: '/ideas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plan': typeof PlanRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plan': typeof PlanRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/ideas': typeof IdeasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plan': typeof PlanRoute
  '/ideas/$id': typeof IdeasIdRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plan' | '/ideas/$id' | '/ideas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plan' | '/ideas/$id' | '/ideas'
  id: '__root__' | '/' | '/plan' | '/ideas/$id' | '/ideas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanRoute: typeof PlanRoute
  IdeasIdRoute: typeof IdeasIdRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$id': {
      id: '/ideas/$id'
      path: '/ideas/$id'
      fullPath: '/ideas/$id'
      preLoaderRoute: typeof IdeasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanRoute: PlanRoute,
  IdeasIdRoute: IdeasIdRoute,
  IdeasIndexRoute: IdeasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
